name: Build Docker - Notebook

on:
  push:
    paths:
      - 'docker/notebook/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
      - name: Docker Build & Push
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notebook:$timestamp -f docker/notebook/Dockerfile ./docker/notebook 
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/notebook:$timestamp ${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notebook:$timestamp
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest